#version: '3.8'

services:
  #SERVER
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: pnpm run start:dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  #DB
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "6000:5432"
    volumes:
        - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
