const ENV = "ENV";
const DB_TYPE = "DB_TYPE";
const DB_HOST = "DB_HOST";
const DB_URL = "DB_URL";
const DB_PORT = "DB_PORT";
const DB_USERNAME = "DB_USERNAME";
const DB_PASSWORD = "DB_PASSWORD";

const DB_DATABASE = "DB_DATABASE";
const HASH_ROUNDS = "HASH_ROUNDS";
const ACCESS_TOKEN_SECRET = "ACCESS_TOKEN_SECRET";
const REFRESH_TOKEN_SECRET = "REFRESH_TOKEN_SECRET";
const AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID";
const AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY";
const AWS_REGION = "AWS_REGION";
const BUCKET_NAME = "BUCKET_NAME";

export const envVariablesKeys = {
  ENV,
  DB_TYPE,
  DB_URL,
  DB_HOST,
  DB_PORT,
  DB_USERNAME,
  DB_PASSWORD,
  DB_DATABASE,
  HASH_ROUNDS,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  BUCKET_NAME,
};
